[tasks.build]
description = "Generates def file and then builds the project"
alias = "b"
run = ["./kotlin task :raylib-kt:generate@build-plugin", "./kotlin build"]
run_windows = ["kotlin.bat task :raylib-kt:generate@build-plugin", "kotlin.bat build"]

[tasks.publish]
description = "Publishes the package to maven central"
alias = "p"
env = { _.file = ".env" }
run = "./kotlin publish mavenCentral"
run_windows = "kotlin.bat publish mavenCentral"

[tasks.publishLocal]
description = "Publishes the package to local maven"
alias = "pl"
env = { _.file = ".env" }
run = "./kotlin publish mavenLocal"
run_windows = "kotlin.bat publish mavenLocal"
